[package]
name = "atlasbuilder"
version = "3.0.0"
authors = ["Pete Ward <peteward44@gmail.com>"]
edition = "2018"

[dependencies]
image = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
clap = "*"
failure = "*"
rand = "*"
png = "*"
oxipng = "*"
